### ISSUE TITLE
Universal Render Pipeline

### ISSUE THREAD

**Issue by flo-wolf** [keijiro/TriplanarPBS#2]
Hello, love the shader!
Is there a URP version available?

**Comment by keijiro** [comment]
You can simply use the Triplanar Node with Shader Graph on URP.

https://docs.unity3d.com/Packages/com.unity.shadergraph@8.1/manual/Triplanar-Node.html

**Comment by flo-wolf** [comment]
Thanks for the reccomendation :) 

Though I thought that the shaders created with shader graph don't support the Unity terrain system...

I need to meet the following requirements:

- Triplanar mapping with mutliple textures (x,y,z different textures)
- Splat mapping
- Compatible with the unity terrain painting/sculpting system
